disabled_rules:
  - trailing_whitespace
  - function_body_length
  - line_length
  - orphaned_doc_comment
  - nesting

opt_in_rules:
  - let_var_whitespace

line_length: 200

file_length:
  warning: 400
  error: 500

type_name:
  min_length: 2

included:
  - DakeAndDevileCorps
excluded:
  - DakeAndDevileCorps/Global/Supports/AppDelegate.swift
  - DakeAndDevileCorps/Global/Supports/SceneDelegate.swift

identifier_name:
  excluded:
    - id

force_cast: warning